pluginName = Changelist Sorter
pluginDescription = Automatically organizes your modified files by moving them into predefined changelists. \
  <br/><br/> \
  Changelist Sorter is a fork and continuation of \
  <a href="https://github.com/4ch1m/ChangelistOrganizer">Changelist Organizer</a> by Achim Seufert, \
  updated for current IntelliJ Platform releases. It is a separate plugin and is not endorsed by the original author.
pluginVersion = 2.0.0
pluginSinceBuild = 252

platformVersion = 2025.2

javaVersion = 21

org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g
